//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContactPerson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactKU
    {
        public string NameCP { get; set; }
        public string PhoneCP { get; set; }
        public string EmailCP { get; set; }
        public string CompanyCP { get; set; }
        public string CountryCP { get; set; }
        public string ZipCodeCP { get; set; }
        public string StatetCP { get; set; }
        public string CityCP { get; set; }
    }
}
